# Block test

## style

In [48]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/style/generated_images/" # Update to your base path # If your paths start with a shared prefix
concepts = ['cyberpunk', 'anime', 'sketch', 'impressionism'] # Add your actual concepts

facts = ['300_1_mean_diff_s_only_pooled', 
         '300_1_mean_diff_s_only_pooled_0_7',
         '300_1_mean_diff_s_only_pooled_0_9',
         '300_1_mean_diff_s_only_pooled_0_12'] # Add your fact identifiers

data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Construct the directory name based on your pattern
        # Adjust the underscores "_" below if your naming convention differs
        
        dir_path = os.path.join(root_dir, concept, fact)
        file_path = os.path.join(dir_path, "summary_metrics.json")
        
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r') as f:
                    metrics = json.load(f)
                
                # Add concept and fact info to the metric dict for tracking
                metrics['concept'] = concept
                metrics['blocks'] = fact
                
                data_list.append(metrics)
                print(f"✅ Loaded: {concept}, {fact}")
            except Exception as e:
                print(f"❌ Error reading {file_path}: {e}")
        else:
            print(f"⚠️ Missing: {dir_path}")

# --- Create Table ---
df = pd.DataFrame(data_list)

# Reorder columns to put Concept and Fact at the front
cols = ['concept', 'blocks'] + [c for c in df.columns if c not in ['concept', 'blocks']]
df = df[cols]

# Save for plotting
df.to_csv("all_metrics_combined.csv", index=False)
print("\n--- Final Data Table ---")
print(df)

✅ Loaded: cyberpunk, 300_1_mean_diff_s_only_pooled
✅ Loaded: cyberpunk, 300_1_mean_diff_s_only_pooled_0_7
✅ Loaded: cyberpunk, 300_1_mean_diff_s_only_pooled_0_9
✅ Loaded: cyberpunk, 300_1_mean_diff_s_only_pooled_0_12
✅ Loaded: anime, 300_1_mean_diff_s_only_pooled
✅ Loaded: anime, 300_1_mean_diff_s_only_pooled_0_7
✅ Loaded: anime, 300_1_mean_diff_s_only_pooled_0_9
✅ Loaded: anime, 300_1_mean_diff_s_only_pooled_0_12
✅ Loaded: sketch, 300_1_mean_diff_s_only_pooled
✅ Loaded: sketch, 300_1_mean_diff_s_only_pooled_0_7
✅ Loaded: sketch, 300_1_mean_diff_s_only_pooled_0_9
✅ Loaded: sketch, 300_1_mean_diff_s_only_pooled_0_12
✅ Loaded: impressionism, 300_1_mean_diff_s_only_pooled
✅ Loaded: impressionism, 300_1_mean_diff_s_only_pooled_0_7
✅ Loaded: impressionism, 300_1_mean_diff_s_only_pooled_0_9
✅ Loaded: impressionism, 300_1_mean_diff_s_only_pooled_0_12

--- Final Data Table ---
     concept    blocks  mean_clip_img_sim  clip_score_concept_target  \
0   cyber...  300_1...  0.781867           0.191460
1   cyber...  300_1...  0.775717           0.194038
2   cyber...  300_1...  0.785289           0.188604
3   cyber...  300_1...  0.788621           0.184892
4      anime  300_1...  0.812990           0.121892
5      anime  300_1...  0.818248           0.114556
6      anime  300_1...  0.831193           0.113559
7      anime  300_1...  0.823514           0.114986
8     sketch  300_1...  0.802958           0.111887
9     sketch  300_1...  0.785020           0.122306
10    sketch  300_1...  0.782575           0.119962
11    sketch  300_1...  0.794669           0.090766
12  impre...  300_1...  0.788538           0.080079
13  impre...  300_1...  0.762233           0.082031
14  impre...  300_1...  0.774417           0.081532
15  impre...  300_1...  0.781764           0.077301

    clip_score_concept_origin  clip_score_all_target  clip_score_all_origin  \
0   0.085515                   0.299962               0.224208
1   0.085515                   0.298978               0.224208
2   0.085515                   0.295061               0.224208
3   0.085515                   0.296546               0.224208
4   0.081271                   0.275770               0.246704
5   0.081271                   0.262858               0.246704
6   0.081271                   0.265301               0.246704
7   0.081271                   0.265245               0.246704
8   0.077158                   0.259875               0.227772
9   0.077158                   0.273234               0.227772
10  0.077158                   0.271188               0.227772
11  0.085515                   0.230135               0.224208
12  0.053927                   0.234389               0.212579
13  0.053927                   0.236549               0.212579
14  0.053927                   0.233699               0.212579
15  0.053927                   0.231047               0.212579

    clip_score_prompt_target  clip_score_prompt_origin
0   0.251652                  0.265622
1   0.248209                  0.265622
2   0.248706                  0.265622
3   0.253507                  0.265622
4   0.270266                  0.265622
5   0.263729                  0.265622
6   0.268293                  0.265622
7   0.265444                  0.265622
8   0.263074                  0.265622
9   0.263430                  0.265622
10  0.264096                  0.265622
11  0.265163                  0.265622
12  0.270585                  0.265622
13  0.267121                  0.265622
14  0.267235                  0.265622
15  0.267412                  0.265622

In [8]:
# 3. Calculate Mean across Concepts for each Fact
# We group by 'fact' and calculate the mean of all numeric metric columns
mean_per_fact = df.groupby('blocks', as_index=False).mean(numeric_only=True)

,blocks,mean_clip_img_sim,clip_score_concept_target,clip_score_concept_origin,clip_score_all_target,clip_score_all_origin,clip_score_prompt_target,clip_score_prompt_origin
0,300_1_mean_diff_...,0.796588,0.126329,0.074468,0.267499,0.227816,0.263894,0.265622
1,300_1_mean_diff_...,0.797142,0.116986,0.076557,0.255743,0.226925,0.262881,0.265622
2,300_1_mean_diff_...,0.785304,0.128233,0.074468,0.267905,0.227816,0.260622,0.265622
3,300_1_mean_diff_...,0.793369,0.125914,0.074468,0.266312,0.227816,0.262083,0.265622

In [15]:
mean_per_fact.columns

Index(['blocks', 'mean_clip_img_sim', 'clip_score_concept_target',
       'clip_score_concept_origin', 'clip_score_all_target',
       'clip_score_all_origin', 'clip_score_prompt_target',
       'clip_score_prompt_origin'],
      dtype='object')

In [17]:
pd.set_option('display.max_colwidth', 9)
mean_per_fact['blocks'] = ['all', '0-7', '0-9', '0-12']
mean_per_fact.drop('mean_clip_img_sim', axis=1, inplace=True)
mean_per_fact

,blocks,clip_score_concept_target,clip_score_concept_origin,clip_score_all_target,clip_score_all_origin,clip_score_prompt_target,clip_score_prompt_origin
0,all,0.126329,0.074468,0.267499,0.227816,0.263894,0.265622
1,0-7,0.116986,0.076557,0.255743,0.226925,0.262881,0.265622
2,0-9,0.128233,0.074468,0.267905,0.227816,0.260622,0.265622
3,0-12,0.125914,0.074468,0.266312,0.227816,0.262083,0.265622

## Add

### clip

In [50]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/add/generated_images/" # Update to your base path # If your paths start with a shared prefix
concepts = ['hat', 'glasses', 'smile', 'lipstick', "apple"] # Add your actual concepts

facts = ['1000_15_mean_diff_s_only_pooled', 
         '1000_15_mean_diff_s_only_pooled_0_7',
         '1000_15_mean_diff_s_only_pooled_0_9',
         '1000_15_mean_diff_s_only_pooled_0_12'] # Add your fact identifiers

data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Construct the directory name based on your pattern
        # Adjust the underscores "_" below if your naming convention differs
        
        dir_path = os.path.join(root_dir, concept, fact)
        file_path = os.path.join(dir_path, "summary_metrics_part.json")
        
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r') as f:
                    metrics = json.load(f)
                
                # Add concept and fact info to the metric dict for tracking
                metrics['concept'] = concept
                metrics['blocks'] = fact
                
                data_list.append(metrics)
                print(f"✅ Loaded: {concept}, {fact}")
            except Exception as e:
                print(f"❌ Error reading {file_path}: {e}")
        else:
            print(f"⚠️ Missing: {dir_path}")

# --- Create Table ---
df = pd.DataFrame(data_list)

# Reorder columns to put Concept and Fact at the front
cols = ['concept', 'blocks'] + [c for c in df.columns if c not in ['concept', 'blocks']]
df = df[cols]

# Save for plotting
df.to_csv("all_metrics_combined.csv", index=False)
print("\n--- Final Data Table ---")
print(df)

✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled
✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled_0_7
✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled_0_12
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled_0_7
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled_0_12
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled_0_7
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled_0_12
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled_0_7
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled_0_12
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled_0_7
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled_0_12

--- Final Data Table ---
     concept    blocks  mean_clip_img_sim  clip_score_concept_target  \
0        hat  1000_...  0.812070           0.190710
1        hat  1000_...  0.843157           0.192560
2        hat  1000_...  0.841010           0.193554
3        hat  1000_...  0.841306           0.188149
4    glasses  1000_...  0.826413           0.173102
5    glasses  1000_...  0.858372           0.180430
6    glasses  1000_...  0.859746           0.178894
7    glasses  1000_...  0.856069           0.178342
8      smile  1000_...  0.868872           0.172808
9      smile  1000_...  0.874777           0.173022
10     smile  1000_...  0.876288           0.172394
11     smile  1000_...  0.870956           0.171975
12  lipstick  1000_...  0.781342           0.187212
13  lipstick  1000_...  0.799090           0.176781
14  lipstick  1000_...  0.793896           0.178436
15  lipstick  1000_...  0.802453           0.180331
16     apple  1000_...  0.830134           0.139420
17     apple  1000_...  0.850915           0.153080
18     apple  1000_...  0.847672           0.152976
19     apple  1000_...  0.859255           0.146538

    clip_score_concept_origin  clip_score_all_target  clip_score_all_origin  \
0   0.127017                   0.272009               0.248536
1   0.127017                   0.284332               0.248536
2   0.127017                   0.280903               0.248536
3   0.127017                   0.280104               0.248536
4   0.107547                   0.274764               0.254187
5   0.107547                   0.289070               0.254187
6   0.107547                   0.286182               0.254187
7   0.107547                   0.286792               0.254187
8   0.139597                   0.266422               0.261553
9   0.139597                   0.272536               0.261553
10  0.139597                   0.270221               0.261553
11  0.139597                   0.267331               0.261553
12  0.114666                   0.262505               0.246188
13  0.114666                   0.259964               0.246188
14  0.114666                   0.264338               0.246188
15  0.114666                   0.267820               0.246188
16  0.124487                   0.258122               0.243110
17  0.124487                   0.278332               0.243110
18  0.124487                   0.279799               0.243110
19  0.124487                   0.273313               0.243110

    clip_score_prompt_target  clip_score_prompt_origin
0   0.246022                  0.268448
1   0.255637                  0.268448
2   0.251915                  0.268448
3   0.253567                  0.268448
4   0.238329                  0.268448
5   0.246978                  0.268448
6   0.245625                  0.268448
7   0.247663                  0.268448
8   0.247892                  0.268448
9   0.252798                  0.268448
10  0.252166                  0.268448
11  0.249150                  0.268448
12  0.232750                  0.268448
13  0.244198                  0.268448
14  0.246177                  0.268448
15  0.248721                  0.268448
16  0.258706                  0.268448
17  0.254989                  0.268448
18  0.255167                  0.268448
19  0.257547                  0.268448

In [44]:
# 3. Calculate Mean across Concepts for each Fact
# We group by 'fact' and calculate the mean of all numeric metric columns

In [51]:
mean_per_fact = df.groupby('blocks', as_index=False).mean(numeric_only=True)

pd.set_option('display.max_colwidth', 9)
mean_per_fact['blocks'] = ['all', '0-7', '0-9', '0-12']
mean_per_fact.drop('mean_clip_img_sim', axis=1, inplace=True)
mean_per_fact

,blocks,clip_score_concept_target,clip_score_concept_origin,clip_score_all_target,clip_score_all_origin,clip_score_prompt_target,clip_score_prompt_origin
0,all,0.172650,0.122663,0.266764,0.250715,0.244740,0.268448
1,0-7,0.173067,0.122663,0.275072,0.250715,0.251329,0.268448
2,0-9,0.175175,0.122663,0.276847,0.250715,0.250920,0.268448
3,0-12,0.175251,0.122663,0.276289,0.250715,0.250210,0.268448

In [26]:
concept_table['blocks'] = ['all', '0-7', '0-9', '0-12']
concept_table.head()

,blocks,clip_score_concept_target,clip_score_all_target,clip_score_prompt_target
8,all,0.161600,0.261387,0.247063
11,0-7,0.160969,0.262918,0.248683
9,0-9,0.161585,0.267142,0.251553
10,0-12,0.161339,0.264743,0.250341

In [52]:
import pandas as pd

# --- Split and Print by Concept ---
print("="*30)
print("DETAILED METRICS BY CONCEPT")
print("="*30)


# Iterate through each unique concept
for concept_name, group in df.groupby('concept'):
    print(f"\n📈 Results for Concept: {concept_name}")
    
    # Select only the relevant columns to keep the printout clean
    # We sort by 'fact' so the comparison is easy to read
    display_cols = ['blocks', 'clip_score_concept_target', 'clip_score_all_target', 'clip_score_prompt_target']
    concept_table = group[display_cols].sort_values(by='blocks')
    
    print(concept_table.to_string(index=False))
    
    # Optional: Save each concept to its own individual CSV
    # concept_table.to_csv(f"metrics_{concept_name.replace(' ', '_')}.csv", index=False)

print("\n" + "="*30)

==============================
DETAILED METRICS BY CONCEPT
==============================

📈 Results for Concept: apple
                              blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
     1000_15_mean_diff_s_only_pooled                   0.139420               0.258122                  0.258706
1000_15_mean_diff_s_only_pooled_0_12                   0.146538               0.273313                  0.257547
 1000_15_mean_diff_s_only_pooled_0_7                   0.153080               0.278332                  0.254989
 1000_15_mean_diff_s_only_pooled_0_9                   0.152976               0.279799                  0.255167

📈 Results for Concept: glasses
                              blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
     1000_15_mean_diff_s_only_pooled                   0.173102               0.274764                  0.238329
1000_15_mean_diff_s_only_pooled_0_12                   0.178342               0.286792                  0.247663
 1000_15_mean_diff_s_only_pooled_0_7                   0.180430               0.289070                  0.246978
 1000_15_mean_diff_s_only_pooled_0_9                   0.178894               0.286182                  0.245625

📈 Results for Concept: hat
                              blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
     1000_15_mean_diff_s_only_pooled                   0.190710               0.272009                  0.246022
1000_15_mean_diff_s_only_pooled_0_12                   0.188149               0.280104                  0.253567
 1000_15_mean_diff_s_only_pooled_0_7                   0.192560               0.284332                  0.255637
 1000_15_mean_diff_s_only_pooled_0_9                   0.193554               0.280903                  0.251915

📈 Results for Concept: lipstick
                              blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
     1000_15_mean_diff_s_only_pooled                   0.187212               0.262505                  0.232750
1000_15_mean_diff_s_only_pooled_0_12                   0.180331               0.267820                  0.248721
 1000_15_mean_diff_s_only_pooled_0_7                   0.176781               0.259964                  0.244198
 1000_15_mean_diff_s_only_pooled_0_9                   0.178436               0.264338                  0.246177

📈 Results for Concept: smile
                              blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
     1000_15_mean_diff_s_only_pooled                   0.172808               0.266422                  0.247892
1000_15_mean_diff_s_only_pooled_0_12                   0.171975               0.267331                  0.249150
 1000_15_mean_diff_s_only_pooled_0_7                   0.173022               0.272536                  0.252798
 1000_15_mean_diff_s_only_pooled_0_9                   0.172394               0.270221                  0.252166

==============================

### grounding dino

In [67]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/add/generated_images/"
concepts = ['hat', 'glasses', 'smile', 'lipstick', "apple"]
facts = [
    '1000_15_mean_diff_s_only_pooled', 
    '1000_15_mean_diff_s_only_pooled_0_7', 
    '1000_15_mean_diff_s_only_pooled_0_9', 
    '1000_15_mean_diff_s_only_pooled_0_12', 
    # '300_1_diff_s', '300_1_diff_m', '300_1_normals_s',
    # '1000_1_diff_s', '1000_1_diff_m', '1000_1_normals_s'
]

# The different threshold files you want to track
thresholds = ['0.25', '0.5', '0.6']
data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Initialize a row with identifier info
        row = {'concept': concept, 'blocks': fact}
        found_any = False
        
        for t in thresholds:
            file_path = os.path.join(root_dir, concept, fact, 'dino', f"metrics_{t}.json")
            print(file_path)
            if os.path.exists(file_path):
                try:
                    with open(file_path, 'r') as f:
                        metrics = json.load(f)
                        # Use the threshold in the key name for clarity
                        row[f'det_rate_{t}'] = metrics.get('detection_rate')
                        found_any = True
                except Exception as e:
                    print(f"❌ Error reading {file_path}: {e}")
        
        if found_any:
            data_list.append(row)
            print(f"✅ Loaded detection metrics for: {concept}, {fact}")
        else:
            print(f"⚠️ Missing all detection files for: {concept}/{fact}")

# --- Create Table ---
df_det = pd.DataFrame(data_list)

# --- Analysis / Grouping ---

experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled/dino/metrics_0.6.json
✅ Loaded detection metrics for: hat, 1000_15_mean_diff_s_only_pooled
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: hat, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.6.json
✅ Loaded detection metrics for: hat, 1000_15_mean_diff_s_only_pooled_0_9
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.6.json
✅ Loaded detection metrics for: hat, 1000_15_mean_diff_s_only_pooled_0_12
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled/dino/metrics_0.6.json
✅ Loaded detection metrics for: glasses, 1000_15_mean_diff_s_only_pooled
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: glasses, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.6.json
✅ Loaded detection metrics for: glasses, 1000_15_mean_diff_s_only_pooled_0_9
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.6.json
✅ Loaded detection metrics for: glasses, 1000_15_mean_diff_s_only_pooled_0_12
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled/dino/metrics_0.6.json
✅ Loaded detection metrics for: smile, 1000_15_mean_diff_s_only_pooled
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: smile, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.6.json
✅ Loaded detection metrics for: smile, 1000_15_mean_diff_s_only_pooled_0_9
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.6.json
✅ Loaded detection metrics for: smile, 1000_15_mean_diff_s_only_pooled_0_12
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled/dino/metrics_0.6.json
✅ Loaded detection metrics for: lipstick, 1000_15_mean_diff_s_only_pooled
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: lipstick, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.6.json
✅ Loaded detection metrics for: lipstick, 1000_15_mean_diff_s_only_pooled_0_9
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.6.json
✅ Loaded detection metrics for: lipstick, 1000_15_mean_diff_s_only_pooled_0_12
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled/dino/metrics_0.6.json
✅ Loaded detection metrics for: apple, 1000_15_mean_diff_s_only_pooled
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: apple, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_9/dino/metrics_0.6.json
✅ Loaded detection metrics for: apple, 1000_15_mean_diff_s_only_pooled_0_9
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_12/dino/metrics_0.6.json
✅ Loaded detection metrics for: apple, 1000_15_mean_diff_s_only_pooled_0_12

In [74]:
# 1. Mean performance per "Block" across all concepts
mean_per_fact['blocks'] = ['all', '0-7', '0-9', '0-12']
mean_per_fact = df_det.groupby('blocks').mean(numeric_only=True)
mean_per_fact['blocks'] = ['all', '0-7', '0-9', '0-12']

pd.set_option('display.max_colwidth', 12)
print("\n--- Detection Rates by Block ---")
mean_per_fact

--- Detection Rates by Block ---

              det_rate_0.25  det_rate_0.5  det_rate_0.6 blocks
blocks
1000_15_m...     0.772414       0.655172      0.565517     all
1000_15_m...     0.806897       0.696552      0.655172     0-7
1000_15_m...     0.813793       0.668966      0.634483     0-9
1000_15_m...     0.820690       0.703448      0.613793    0-12

## Switch

### CLIP

In [3]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/switch/generated_images/" # Update to your base path # If your paths start with a shared prefix
concepts = ['cat_dog', 'apple_banana', 'kettle_vase', "age", "gender"] # Add your actual concepts

facts = ['1000_3_mean_diff_s_only_pooled', 
         '1000_3_mean_diff_s_only_pooled_0_7',
         '1000_3_mean_diff_s_only_pooled_0_9',
         '1000_3_mean_diff_s_only_pooled_0_12'] # Add your fact identifiers

data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Construct the directory name based on your pattern
        # Adjust the underscores "_" below if your naming convention differs
        
        dir_path = os.path.join(root_dir, concept, fact)
        file_path = os.path.join(dir_path, "summary_metrics_part.json")
        
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r') as f:
                    metrics = json.load(f)
                
                # Add concept and fact info to the metric dict for tracking
                metrics['concept'] = concept
                metrics['blocks'] = fact
                
                data_list.append(metrics)
                print(f"✅ Loaded: {concept}, {fact}")
            except Exception as e:
                print(f"❌ Error reading {file_path}: {e}")
        else:
            print(f"⚠️ Missing: {dir_path}")

# --- Create Table ---
df = pd.DataFrame(data_list)

# Reorder columns to put Concept and Fact at the front
cols = ['concept', 'blocks'] + [c for c in df.columns if c not in ['concept', 'blocks']]
df = df[cols]

# Save for plotting
df.to_csv("all_metrics_combined.csv", index=False)
print("\n--- Final Data Table ---")
print(df)

✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled
✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled_0_9
✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled_0_12
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled_0_9
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled_0_12
⚠️ Missing: experiments/flux_schnell/switch/generated_images/kettle_vase/1000_3_mean_diff_s_only_pooled
✅ Loaded: kettle_vase, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: kettle_vase, 1000_3_mean_diff_s_only_pooled_0_9
✅ Loaded: kettle_vase, 1000_3_mean_diff_s_only_pooled_0_12
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled_0_9
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled_0_12
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled_0_9
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled_0_12

--- Final Data Table ---
         concept                               blocks  mean_clip_img_sim  \
0        cat_dog       1000_3_mean_diff_s_only_pooled           0.772960
1        cat_dog   1000_3_mean_diff_s_only_pooled_0_7           0.795101
2        cat_dog   1000_3_mean_diff_s_only_pooled_0_9           0.792481
3        cat_dog  1000_3_mean_diff_s_only_pooled_0_12           0.796751
4   apple_banana       1000_3_mean_diff_s_only_pooled           0.845017
5   apple_banana   1000_3_mean_diff_s_only_pooled_0_7           0.856774
6   apple_banana   1000_3_mean_diff_s_only_pooled_0_9           0.866010
7   apple_banana  1000_3_mean_diff_s_only_pooled_0_12           0.868038
8    kettle_vase   1000_3_mean_diff_s_only_pooled_0_7           0.718507
9    kettle_vase   1000_3_mean_diff_s_only_pooled_0_9           0.735198
10   kettle_vase  1000_3_mean_diff_s_only_pooled_0_12           0.744853
11           age       1000_3_mean_diff_s_only_pooled           0.585589
12           age   1000_3_mean_diff_s_only_pooled_0_7           0.676310
13           age   1000_3_mean_diff_s_only_pooled_0_9           0.652370
14           age  1000_3_mean_diff_s_only_pooled_0_12           0.622585
15        gender       1000_3_mean_diff_s_only_pooled           0.698950
16        gender   1000_3_mean_diff_s_only_pooled_0_7           0.716356
17        gender   1000_3_mean_diff_s_only_pooled_0_9           0.698171
18        gender  1000_3_mean_diff_s_only_pooled_0_12           0.718572

    clip_score_concept_target  clip_score_concept_origin  \
0                    0.223119                   0.147153
1                    0.222697                   0.147153
2                    0.225943                   0.147153
3                    0.221538                   0.147153
4                    0.224846                   0.170459
5                    0.218796                   0.170459
6                    0.216995                   0.170459
7                    0.213225                   0.170459
8                    0.220656                   0.150116
9                    0.211761                   0.150116
10                   0.213882                   0.150116
11                   0.177664                   0.149149
12                   0.187028                   0.149149
13                   0.185348                   0.149149
14                   0.183669                   0.149149
15                   0.162243                   0.095886
16                   0.150182                   0.095886
17                   0.153397                   0.095886
18                   0.158188                   0.095886

    clip_score_all_target  clip_score_all_origin  clip_score_prompt_target  \
0                0.276395               0.220889                  0.189378
1                0.290948               0.220889                  0.203728
2                0.292802               0.220889                  0.205177
3                0.289271               0.220889                  0.200778
4                0.278652               0.224809                  0.211057
5                0.281358               0.224809                  0.207795
6                0.275262               0.224809                  0.221449
7                0.273862               0.224809                  0.220665
8                0.260070               0.228619                  0.180751
9                0.257456               0.228619                  0.190812
10               0.258462               0.228619                  0.193083
11               0.259448               0.212237                  0.223524
12               0.281040               0.212237                  0.237898
13               0.281382               0.212237                  0.237279
14               0.270591               0.212237                  0.231220
15               0.225194               0.196829                  0.177048
16               0.240737               0.196829                  0.187596
17               0.231011               0.196829                  0.174022
18               0.232192               0.196829                  0.177587

    clip_score_prompt_origin
0                   0.289638
1                   0.289638
2                   0.289638
3                   0.289638
4                   0.295799
5                   0.295799
6                   0.295799
7                   0.295799
8                   0.281521
9                   0.281521
10                  0.281521
11                  0.266645
12                  0.266645
13                  0.266645
14                  0.266645
15                  0.248786
16                  0.248786
17                  0.248786
18                  0.248786

In [4]:
mean_per_fact = df.groupby('blocks', as_index=False).mean(numeric_only=True)

pd.set_option('display.max_colwidth', 9)
mean_per_fact['blocks'] = ['all', '0-7', '0-9', '0-12']
mean_per_fact.drop('mean_clip_img_sim', axis=1, inplace=True)
mean_per_fact

,blocks,clip_score_concept_target,clip_score_concept_origin,clip_score_all_target,clip_score_all_origin,clip_score_prompt_target,clip_score_prompt_origin
0,all,0.196968,0.140662,0.259923,0.213691,0.200252,0.275217
1,0-7,0.198101,0.142553,0.264875,0.216677,0.204667,0.276478
2,0-9,0.199872,0.142553,0.270831,0.216677,0.203554,0.276478
3,0-12,0.198689,0.142553,0.267583,0.216677,0.205748,0.276478

In [5]:
import pandas as pd

# --- Split and Print by Concept ---
print("="*30)
print("DETAILED METRICS BY CONCEPT")
print("="*30)


# Iterate through each unique concept
for concept_name, group in df.groupby('concept'):
    print(f"\n📈 Results for Concept: {concept_name}")
    
    # Select only the relevant columns to keep the printout clean
    # We sort by 'fact' so the comparison is easy to read
    display_cols = ['blocks', 'clip_score_concept_target', 'clip_score_all_target', 'clip_score_prompt_target', "clip_score_prompt_origin", "clip_score_all_origin"]
    concept_table = group[display_cols].sort_values(by='blocks')
    
    print(concept_table.to_string(index=False))
    
    # Optional: Save each concept to its own individual CSV
    # concept_table.to_csv(f"metrics_{concept_name.replace(' ', '_')}.csv", index=False)

print("\n" + "="*30)

==============================
DETAILED METRICS BY CONCEPT
==============================

📈 Results for Concept: age
                             blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
     1000_3_mean_diff_s_only_pooled                   0.177664               0.259448                  0.223524                  0.266645               0.212237
1000_3_mean_diff_s_only_pooled_0_12                   0.183669               0.270591                  0.231220                  0.266645               0.212237
 1000_3_mean_diff_s_only_pooled_0_7                   0.187028               0.281040                  0.237898                  0.266645               0.212237
 1000_3_mean_diff_s_only_pooled_0_9                   0.185348               0.281382                  0.237279                  0.266645               0.212237

📈 Results for Concept: apple_banana
                             blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
     1000_3_mean_diff_s_only_pooled                   0.224846               0.278652                  0.211057                  0.295799               0.224809
1000_3_mean_diff_s_only_pooled_0_12                   0.213225               0.273862                  0.220665                  0.295799               0.224809
 1000_3_mean_diff_s_only_pooled_0_7                   0.218796               0.281358                  0.207795                  0.295799               0.224809
 1000_3_mean_diff_s_only_pooled_0_9                   0.216995               0.275262                  0.221449                  0.295799               0.224809

📈 Results for Concept: cat_dog
                             blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
     1000_3_mean_diff_s_only_pooled                   0.223119               0.276395                  0.189378                  0.289638               0.220889
1000_3_mean_diff_s_only_pooled_0_12                   0.221538               0.289271                  0.200778                  0.289638               0.220889
 1000_3_mean_diff_s_only_pooled_0_7                   0.222697               0.290948                  0.203728                  0.289638               0.220889
 1000_3_mean_diff_s_only_pooled_0_9                   0.225943               0.292802                  0.205177                  0.289638               0.220889

📈 Results for Concept: gender
                             blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
     1000_3_mean_diff_s_only_pooled                   0.162243               0.225194                  0.177048                  0.248786               0.196829
1000_3_mean_diff_s_only_pooled_0_12                   0.158188               0.232192                  0.177587                  0.248786               0.196829
 1000_3_mean_diff_s_only_pooled_0_7                   0.150182               0.240737                  0.187596                  0.248786               0.196829
 1000_3_mean_diff_s_only_pooled_0_9                   0.153397               0.231011                  0.174022                  0.248786               0.196829

📈 Results for Concept: kettle_vase
                             blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
1000_3_mean_diff_s_only_pooled_0_12                   0.213882               0.258462                  0.193083                  0.281521               0.228619
 1000_3_mean_diff_s_only_pooled_0_7                   0.220656               0.260070                  0.180751                  0.281521               0.228619
 1000_3_mean_diff_s_only_pooled_0_9                   0.211761               0.257456                  0.190812                  0.281521               0.228619

==============================

# Timesteps test

## add

In [54]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/add/generated_images/" # Update to your base path # If your paths start with a shared prefix
concepts = ['hat', 'glasses', 'smile', 'lipstick', "apple"] # Add your actual concepts

facts = ['1000_15_mean_diff_s_only_pooled_0_9', 
         '1000_15_mean_diff_s_only_pooled_0_9_0',
         '1000_15_mean_diff_s_only_pooled_0_9_0_1',
         '1000_15_mean_diff_s_only_pooled_0_9_2_3',
         '1000_15_mean_diff_s_only_pooled_0_9_one_vec'] # Add your fact identifiers

data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Construct the directory name based on your pattern
        # Adjust the underscores "_" below if your naming convention differs
        
        dir_path = os.path.join(root_dir, concept, fact)
        file_path = os.path.join(dir_path, "summary_metrics_part.json")
        
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r') as f:
                    metrics = json.load(f)
                
                # Add concept and fact info to the metric dict for tracking
                metrics['concept'] = concept
                metrics['blocks'] = fact
                
                data_list.append(metrics)
                print(f"✅ Loaded: {concept}, {fact}")
            except Exception as e:
                print(f"❌ Error reading {file_path}: {e}")
        else:
            print(f"⚠️ Missing: {dir_path}")

# --- Create Table ---
df = pd.DataFrame(data_list)

# Reorder columns to put Concept and Fact at the front
cols = ['concept', 'blocks'] + [c for c in df.columns if c not in ['concept', 'blocks']]
df = df[cols]

# Save for plotting
df.to_csv("all_metrics_combined.csv", index=False)
print("\n--- Final Data Table ---")
print(df)

✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled_0_9_0
✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled_0_9_0_1
✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled_0_9_2_3
✅ Loaded: hat, 1000_15_mean_diff_s_only_pooled_0_9_one_vec
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled_0_9_0
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled_0_9_0_1
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled_0_9_2_3
✅ Loaded: glasses, 1000_15_mean_diff_s_only_pooled_0_9_one_vec
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled_0_9_0
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled_0_9_0_1
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled_0_9_2_3
✅ Loaded: smile, 1000_15_mean_diff_s_only_pooled_0_9_one_vec
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled_0_9_0
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled_0_9_0_1
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled_0_9_2_3
✅ Loaded: lipstick, 1000_15_mean_diff_s_only_pooled_0_9_one_vec
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled_0_9
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled_0_9_0
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled_0_9_0_1
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled_0_9_2_3
✅ Loaded: apple, 1000_15_mean_diff_s_only_pooled_0_9_one_vec

--- Final Data Table ---
     concept    blocks  mean_clip_img_sim  clip_score_concept_target  \
0        hat  1000_...  0.841010           0.193554
1        hat  1000_...  0.843374           0.193682
2        hat  1000_...  0.841013           0.193072
3        hat  1000_...  0.921312           0.154251
4        hat  1000_...  0.838847           0.192980
5    glasses  1000_...  0.859746           0.178894
6    glasses  1000_...  0.859779           0.177759
7    glasses  1000_...  0.859166           0.177656
8    glasses  1000_...  0.943333           0.129257
9    glasses  1000_...  0.858308           0.178274
10     smile  1000_...  0.876288           0.172394
11     smile  1000_...  0.874027           0.171911
12     smile  1000_...  0.875087           0.172283
13     smile  1000_...  0.940808           0.164884
14     smile  1000_...  0.876439           0.171971
15  lipstick  1000_...  0.793896           0.178436
16  lipstick  1000_...  0.799390           0.174903
17  lipstick  1000_...  0.795857           0.177072
18  lipstick  1000_...  0.935177           0.126538
19  lipstick  1000_...  0.791878           0.178275
20     apple  1000_...  0.847672           0.152976
21     apple  1000_...  0.850044           0.143681
22     apple  1000_...  0.845972           0.151472
23     apple  1000_...  0.947757           0.129607
24     apple  1000_...  0.845932           0.152058

    clip_score_concept_origin  clip_score_all_target  clip_score_all_origin  \
0   0.127017                   0.280903               0.248536
1   0.127017                   0.281352               0.248536
2   0.127017                   0.280103               0.248536
3   0.127017                   0.263084               0.248536
4   0.127017                   0.280148               0.248536
5   0.107547                   0.286182               0.254187
6   0.107547                   0.284725               0.254187
7   0.107547                   0.285090               0.254187
8   0.107547                   0.266725               0.254187
9   0.107547                   0.285322               0.254187
10  0.139597                   0.270221               0.261553
11  0.139597                   0.269684               0.261553
12  0.139597                   0.270507               0.261553
13  0.139597                   0.272536               0.261553
14  0.139597                   0.270105               0.261553
15  0.114666                   0.264338               0.246188
16  0.114666                   0.263175               0.246188
17  0.114666                   0.263661               0.246188
18  0.114666                   0.256519               0.246188
19  0.114666                   0.263882               0.246188
20  0.124487                   0.279799               0.243110
21  0.124487                   0.265939               0.243110
22  0.124487                   0.275733               0.243110
23  0.124487                   0.251120               0.243110
24  0.124487                   0.276234               0.243110

    clip_score_prompt_target  clip_score_prompt_origin
0   0.251915                  0.268448
1   0.252048                  0.268448
2   0.251279                  0.268448
3   0.265550                  0.268448
4   0.251583                  0.268448
5   0.245625                  0.268448
6   0.244098                  0.268448
7   0.244565                  0.268448
8   0.264500                  0.268448
9   0.244281                  0.268448
10  0.252166                  0.268448
11  0.251821                  0.268448
12  0.252400                  0.268448
13  0.261838                  0.268448
14  0.252255                  0.268448
15  0.246177                  0.268448
16  0.246459                  0.268448
17  0.246128                  0.268448
18  0.271786                  0.268448
19  0.244437                  0.268448
20  0.255167                  0.268448
21  0.255273                  0.268448
22  0.253060                  0.268448
23  0.274087                  0.268448
24  0.254336                  0.268448

In [55]:
mean_per_fact = df.groupby('blocks', as_index=False).mean(numeric_only=True)

pd.set_option('display.max_colwidth', 9)
mean_per_fact['blocks'] = ['all', '0', '0-1', '2-3', 'one vec']
mean_per_fact.drop('mean_clip_img_sim', axis=1, inplace=True)
mean_per_fact

,blocks,clip_score_concept_target,clip_score_concept_origin,clip_score_all_target,clip_score_all_origin,clip_score_prompt_target,clip_score_prompt_origin
0,all,0.175251,0.122663,0.276289,0.250715,0.250210,0.268448
1,0,0.172387,0.122663,0.272975,0.250715,0.249940,0.268448
2,0-1,0.174311,0.122663,0.275019,0.250715,0.249486,0.268448
3,2-3,0.140907,0.122663,0.261997,0.250715,0.267552,0.268448
4,one vec,0.174712,0.122663,0.275138,0.250715,0.249378,0.268448

In [56]:
import pandas as pd

# --- Split and Print by Concept ---
print("="*30)
print("DETAILED METRICS BY CONCEPT")
print("="*30)


# Iterate through each unique concept
for concept_name, group in df.groupby('concept'):
    print(f"\n📈 Results for Concept: {concept_name}")
    
    # Select only the relevant columns to keep the printout clean
    # We sort by 'fact' so the comparison is easy to read
    display_cols = ['blocks', 'clip_score_concept_target', 'clip_score_all_target', 'clip_score_prompt_target']
    concept_table = group[display_cols].sort_values(by='blocks')
    
    print(concept_table.to_string(index=False))
    
    # Optional: Save each concept to its own individual CSV
    # concept_table.to_csv(f"metrics_{concept_name.replace(' ', '_')}.csv", index=False)

print("\n" + "="*30)

==============================
DETAILED METRICS BY CONCEPT
==============================

📈 Results for Concept: apple
                                     blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
        1000_15_mean_diff_s_only_pooled_0_9                   0.152976               0.279799                  0.255167
      1000_15_mean_diff_s_only_pooled_0_9_0                   0.143681               0.265939                  0.255273
    1000_15_mean_diff_s_only_pooled_0_9_0_1                   0.151472               0.275733                  0.253060
    1000_15_mean_diff_s_only_pooled_0_9_2_3                   0.129607               0.251120                  0.274087
1000_15_mean_diff_s_only_pooled_0_9_one_vec                   0.152058               0.276234                  0.254336

📈 Results for Concept: glasses
                                     blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
        1000_15_mean_diff_s_only_pooled_0_9                   0.178894               0.286182                  0.245625
      1000_15_mean_diff_s_only_pooled_0_9_0                   0.177759               0.284725                  0.244098
    1000_15_mean_diff_s_only_pooled_0_9_0_1                   0.177656               0.285090                  0.244565
    1000_15_mean_diff_s_only_pooled_0_9_2_3                   0.129257               0.266725                  0.264500
1000_15_mean_diff_s_only_pooled_0_9_one_vec                   0.178274               0.285322                  0.244281

📈 Results for Concept: hat
                                     blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
        1000_15_mean_diff_s_only_pooled_0_9                   0.193554               0.280903                  0.251915
      1000_15_mean_diff_s_only_pooled_0_9_0                   0.193682               0.281352                  0.252048
    1000_15_mean_diff_s_only_pooled_0_9_0_1                   0.193072               0.280103                  0.251279
    1000_15_mean_diff_s_only_pooled_0_9_2_3                   0.154251               0.263084                  0.265550
1000_15_mean_diff_s_only_pooled_0_9_one_vec                   0.192980               0.280148                  0.251583

📈 Results for Concept: lipstick
                                     blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
        1000_15_mean_diff_s_only_pooled_0_9                   0.178436               0.264338                  0.246177
      1000_15_mean_diff_s_only_pooled_0_9_0                   0.174903               0.263175                  0.246459
    1000_15_mean_diff_s_only_pooled_0_9_0_1                   0.177072               0.263661                  0.246128
    1000_15_mean_diff_s_only_pooled_0_9_2_3                   0.126538               0.256519                  0.271786
1000_15_mean_diff_s_only_pooled_0_9_one_vec                   0.178275               0.263882                  0.244437

📈 Results for Concept: smile
                                     blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
        1000_15_mean_diff_s_only_pooled_0_9                   0.172394               0.270221                  0.252166
      1000_15_mean_diff_s_only_pooled_0_9_0                   0.171911               0.269684                  0.251821
    1000_15_mean_diff_s_only_pooled_0_9_0_1                   0.172283               0.270507                  0.252400
    1000_15_mean_diff_s_only_pooled_0_9_2_3                   0.164884               0.272536                  0.261838
1000_15_mean_diff_s_only_pooled_0_9_one_vec                   0.171971               0.270105                  0.252255

==============================

## style

## switch

In [6]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/switch/generated_images/" # Update to your base path # If your paths start with a shared prefix
concepts = ['cat_dog', 'apple_banana', 'kettle_vase', "age", "gender"] # Add your actual concepts

facts = ['1000_3_mean_diff_s_only_pooled_0_7',
         '1000_3_mean_diff_s_only_pooled_0_7_0', 
         '1000_3_mean_diff_s_only_pooled_0_7_0_1',
         '1000_3_mean_diff_s_only_pooled_0_7_2_3',
         '1000_3_mean_diff_s_only_pooled_0_7_one_vec'] # Add your fact identifiers

data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Construct the directory name based on your pattern
        # Adjust the underscores "_" below if your naming convention differs
        
        dir_path = os.path.join(root_dir, concept, fact)
        file_path = os.path.join(dir_path, "summary_metrics_part.json")
        
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r') as f:
                    metrics = json.load(f)
                
                # Add concept and fact info to the metric dict for tracking
                metrics['concept'] = concept
                metrics['blocks'] = fact
                
                data_list.append(metrics)
                print(f"✅ Loaded: {concept}, {fact}")
            except Exception as e:
                print(f"❌ Error reading {file_path}: {e}")
        else:
            print(f"⚠️ Missing: {dir_path}")

# --- Create Table ---
df = pd.DataFrame(data_list)

# Reorder columns to put Concept and Fact at the front
cols = ['concept', 'blocks'] + [c for c in df.columns if c not in ['concept', 'blocks']]
df = df[cols]

# Save for plotting
df.to_csv("all_metrics_combined.csv", index=False)
print("\n--- Final Data Table ---")
print(df)

✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled_0_7_0
✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled_0_7_0_1
✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled_0_7_2_3
✅ Loaded: cat_dog, 1000_3_mean_diff_s_only_pooled_0_7_one_vec
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled_0_7_0
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled_0_7_0_1
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled_0_7_2_3
✅ Loaded: apple_banana, 1000_3_mean_diff_s_only_pooled_0_7_one_vec
✅ Loaded: kettle_vase, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: kettle_vase, 1000_3_mean_diff_s_only_pooled_0_7_0
✅ Loaded: kettle_vase, 1000_3_mean_diff_s_only_pooled_0_7_0_1
⚠️ Missing: experiments/flux_schnell/switch/generated_images/kettle_vase/1000_3_mean_diff_s_only_pooled_0_7_2_3
✅ Loaded: kettle_vase, 1000_3_mean_diff_s_only_pooled_0_7_one_vec
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled_0_7_0
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled_0_7_0_1
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled_0_7_2_3
✅ Loaded: age, 1000_3_mean_diff_s_only_pooled_0_7_one_vec
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled_0_7
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled_0_7_0
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled_0_7_0_1
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled_0_7_2_3
✅ Loaded: gender, 1000_3_mean_diff_s_only_pooled_0_7_one_vec

--- Final Data Table ---
     concept    blocks  mean_clip_img_sim  clip_score_concept_target  \
0    cat_dog  1000_...  0.795101           0.222697
1    cat_dog  1000_...  0.794095           0.223455
2    cat_dog  1000_...  0.794775           0.223461
3    cat_dog  1000_...  0.859189           0.214854
4    cat_dog  1000_...  0.791894           0.223257
5   apple...  1000_...  0.856774           0.218796
6   apple...  1000_...  0.849766           0.221511
7   apple...  1000_...  0.854915           0.220370
8   apple...  1000_...  0.930203           0.185281
9   apple...  1000_...  0.855501           0.218214
10  kettl...  1000_...  0.718507           0.220656
11  kettl...  1000_...  0.720601           0.219579
12  kettl...  1000_...  0.721072           0.219956
13  kettl...  1000_...  0.713983           0.221165
14       age  1000_...  0.676310           0.187028
15       age  1000_...  0.671490           0.185949
16       age  1000_...  0.682019           0.186900
17       age  1000_...  0.753451           0.167898
18       age  1000_...  0.677951           0.187754
19    gender  1000_...  0.716356           0.150182
20    gender  1000_...  0.722740           0.153571
21    gender  1000_...  0.721081           0.152383
22    gender  1000_...  0.887326           0.111467
23    gender  1000_...  0.716153           0.152656

    clip_score_concept_origin  clip_score_all_target  clip_score_all_origin  \
0   0.147153                   0.290948               0.220889
1   0.147153                   0.292460               0.220889
2   0.147153                   0.291095               0.220889
3   0.147153                   0.299036               0.220889
4   0.147153                   0.289821               0.220889
5   0.170459                   0.281358               0.224809
6   0.170459                   0.284262               0.224809
7   0.170459                   0.282121               0.224809
8   0.170459                   0.241552               0.224809
9   0.170459                   0.281820               0.224809
10  0.150116                   0.260070               0.228619
11  0.150116                   0.259009               0.228619
12  0.150116                   0.258417               0.228619
13  0.150116                   0.261736               0.228619
14  0.149149                   0.281040               0.212237
15  0.149149                   0.279345               0.212237
16  0.149149                   0.279723               0.212237
17  0.149149                   0.254158               0.212237
18  0.149149                   0.281778               0.212237
19  0.095886                   0.240737               0.196829
20  0.095886                   0.244970               0.196829
21  0.095886                   0.243156               0.196829
22  0.095886                   0.214015               0.196829
23  0.095886                   0.242839               0.196829

    clip_score_prompt_target  clip_score_prompt_origin
0   0.203728                  0.289638
1   0.205594                  0.289638
2   0.203950                  0.289638
3   0.234047                  0.289638
4   0.203150                  0.289638
5   0.207795                  0.295799
6   0.209762                  0.295799
7   0.208623                  0.295799
8   0.293281                  0.295799
9   0.207289                  0.295799
10  0.180751                  0.281521
11  0.181514                  0.281521
12  0.180310                  0.281521
13  0.183012                  0.281521
14  0.237898                  0.266645
15  0.235561                  0.266645
16  0.236540                  0.266645
17  0.236703                  0.266645
18  0.238506                  0.266645
19  0.187596                  0.248786
20  0.191440                  0.248786
21  0.190479                  0.248786
22  0.245909                  0.248786
23  0.189277                  0.248786

In [7]:
mean_per_fact = df.groupby('blocks', as_index=False).mean(numeric_only=True)

pd.set_option('display.max_colwidth', 9)
mean_per_fact['blocks'] = ['all', '0', '0-1', '2-3', 'one vec']
mean_per_fact.drop('mean_clip_img_sim', axis=1, inplace=True)
mean_per_fact

,blocks,clip_score_concept_target,clip_score_concept_origin,clip_score_all_target,clip_score_all_origin,clip_score_prompt_target,clip_score_prompt_origin
0,all,0.199872,0.142553,0.270831,0.216677,0.203554,0.276478
1,0,0.200813,0.142553,0.272009,0.216677,0.204774,0.276478
2,0-1,0.200614,0.142553,0.270902,0.216677,0.203981,0.276478
3,2-3,0.169875,0.140662,0.252190,0.213691,0.252485,0.275217
4,one vec,0.200609,0.142553,0.271599,0.216677,0.204247,0.276478

In [9]:
import pandas as pd

# --- Split and Print by Concept ---
print("="*30)
print("DETAILED METRICS BY CONCEPT")
print("="*30)


# Iterate through each unique concept
for concept_name, group in df.groupby('concept'):
    print(f"\n📈 Results for Concept: {concept_name}")
    
    # Select only the relevant columns to keep the printout clean
    # We sort by 'fact' so the comparison is easy to read
    display_cols = ['blocks', 'clip_score_concept_target', 'clip_score_all_target', 'clip_score_prompt_target', "clip_score_prompt_origin", "clip_score_all_origin"]
    concept_table = group[display_cols].sort_values(by='blocks')
    
    print(concept_table.to_string(index=False))
    
    # Optional: Save each concept to its own individual CSV
    # concept_table.to_csv(f"metrics_{concept_name.replace(' ', '_')}.csv", index=False)

print("\n" + "="*30)

==============================
DETAILED METRICS BY CONCEPT
==============================

📈 Results for Concept: age
                                    blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
        1000_3_mean_diff_s_only_pooled_0_7                   0.187028               0.281040                  0.237898                  0.266645               0.212237
      1000_3_mean_diff_s_only_pooled_0_7_0                   0.185949               0.279345                  0.235561                  0.266645               0.212237
    1000_3_mean_diff_s_only_pooled_0_7_0_1                   0.186900               0.279723                  0.236540                  0.266645               0.212237
    1000_3_mean_diff_s_only_pooled_0_7_2_3                   0.167898               0.254158                  0.236703                  0.266645               0.212237
1000_3_mean_diff_s_only_pooled_0_7_one_vec                   0.187754               0.281778                  0.238506                  0.266645               0.212237

📈 Results for Concept: apple_banana
                                    blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
        1000_3_mean_diff_s_only_pooled_0_7                   0.218796               0.281358                  0.207795                  0.295799               0.224809
      1000_3_mean_diff_s_only_pooled_0_7_0                   0.221511               0.284262                  0.209762                  0.295799               0.224809
    1000_3_mean_diff_s_only_pooled_0_7_0_1                   0.220370               0.282121                  0.208623                  0.295799               0.224809
    1000_3_mean_diff_s_only_pooled_0_7_2_3                   0.185281               0.241552                  0.293281                  0.295799               0.224809
1000_3_mean_diff_s_only_pooled_0_7_one_vec                   0.218214               0.281820                  0.207289                  0.295799               0.224809

📈 Results for Concept: cat_dog
                                    blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
        1000_3_mean_diff_s_only_pooled_0_7                   0.222697               0.290948                  0.203728                  0.289638               0.220889
      1000_3_mean_diff_s_only_pooled_0_7_0                   0.223455               0.292460                  0.205594                  0.289638               0.220889
    1000_3_mean_diff_s_only_pooled_0_7_0_1                   0.223461               0.291095                  0.203950                  0.289638               0.220889
    1000_3_mean_diff_s_only_pooled_0_7_2_3                   0.214854               0.299036                  0.234047                  0.289638               0.220889
1000_3_mean_diff_s_only_pooled_0_7_one_vec                   0.223257               0.289821                  0.203150                  0.289638               0.220889

📈 Results for Concept: gender
                                    blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
        1000_3_mean_diff_s_only_pooled_0_7                   0.150182               0.240737                  0.187596                  0.248786               0.196829
      1000_3_mean_diff_s_only_pooled_0_7_0                   0.153571               0.244970                  0.191440                  0.248786               0.196829
    1000_3_mean_diff_s_only_pooled_0_7_0_1                   0.152383               0.243156                  0.190479                  0.248786               0.196829
    1000_3_mean_diff_s_only_pooled_0_7_2_3                   0.111467               0.214015                  0.245909                  0.248786               0.196829
1000_3_mean_diff_s_only_pooled_0_7_one_vec                   0.152656               0.242839                  0.189277                  0.248786               0.196829

📈 Results for Concept: kettle_vase
                                    blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target  clip_score_prompt_origin  clip_score_all_origin
        1000_3_mean_diff_s_only_pooled_0_7                   0.220656               0.260070                  0.180751                  0.281521               0.228619
      1000_3_mean_diff_s_only_pooled_0_7_0                   0.219579               0.259009                  0.181514                  0.281521               0.228619
    1000_3_mean_diff_s_only_pooled_0_7_0_1                   0.219956               0.258417                  0.180310                  0.281521               0.228619
1000_3_mean_diff_s_only_pooled_0_7_one_vec                   0.221165               0.261736                  0.183012                  0.281521               0.228619

==============================

# Strength test

## Switch

### clip

In [11]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/switch/generated_images/" # Update to your base path # If your paths start with a shared prefix
concepts = ['cat_dog', 'apple_banana', 'kettle_vase', "age", "gender"] # Add your actual concepts

facts = ['0_2', 
         '300_2_diff_s',
         '300_2_diff_m',
         '300_2_normals_s',
         '1000_2_diff_s',
         '1000_2_diff_m',
         '1000_2_normals_s',

         ] # 
data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Construct the directory name based on your pattern
        # Adjust the underscores "_" below if your naming convention differs
        
        dir_path = os.path.join(root_dir, concept, fact)
        file_path = os.path.join(dir_path, "summary_metrics_part.json")
        
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r') as f:
                    metrics = json.load(f)
                
                # Add concept and fact info to the metric dict for tracking
                metrics['concept'] = concept
                metrics['blocks'] = fact
                
                data_list.append(metrics)
                print(f"✅ Loaded: {concept}, {fact}")
            except Exception as e:
                print(f"❌ Error reading {file_path}: {e}")
        else:
            print(f"⚠️ Missing: {dir_path}")

# --- Create Table ---
df = pd.DataFrame(data_list)

# Reorder columns to put Concept and Fact at the front
cols = ['concept', 'blocks'] + [c for c in df.columns if c not in ['concept', 'blocks']]
df = df[cols]

# Save for plotting
df.to_csv("all_metrics_combined.csv", index=False)
print("\n--- Final Data Table ---")
print(df)

✅ Loaded: cat_dog, 0_2
✅ Loaded: cat_dog, 300_2_diff_s
✅ Loaded: cat_dog, 300_2_diff_m
✅ Loaded: cat_dog, 300_2_normals_s
✅ Loaded: cat_dog, 1000_2_diff_s
✅ Loaded: cat_dog, 1000_2_diff_m
✅ Loaded: cat_dog, 1000_2_normals_s
✅ Loaded: apple_banana, 0_2
✅ Loaded: apple_banana, 300_2_diff_s
✅ Loaded: apple_banana, 300_2_diff_m
✅ Loaded: apple_banana, 300_2_normals_s
✅ Loaded: apple_banana, 1000_2_diff_s
✅ Loaded: apple_banana, 1000_2_diff_m
✅ Loaded: apple_banana, 1000_2_normals_s
✅ Loaded: kettle_vase, 0_2
✅ Loaded: kettle_vase, 300_2_diff_s
✅ Loaded: kettle_vase, 300_2_diff_m
✅ Loaded: kettle_vase, 300_2_normals_s
✅ Loaded: kettle_vase, 1000_2_diff_s
✅ Loaded: kettle_vase, 1000_2_diff_m
✅ Loaded: kettle_vase, 1000_2_normals_s
✅ Loaded: age, 0_2
✅ Loaded: age, 300_2_diff_s
✅ Loaded: age, 300_2_diff_m
✅ Loaded: age, 300_2_normals_s
✅ Loaded: age, 1000_2_diff_s
✅ Loaded: age, 1000_2_diff_m
✅ Loaded: age, 1000_2_normals_s
✅ Loaded: gender, 0_2
✅ Loaded: gender, 300_2_diff_s
✅ Loaded: gender, 300_2_diff_m
✅ Loaded: gender, 300_2_normals_s
✅ Loaded: gender, 1000_2_diff_s
✅ Loaded: gender, 1000_2_diff_m
✅ Loaded: gender, 1000_2_normals_s

--- Final Data Table ---
     concept    blocks  mean_clip_img_sim  clip_score_concept_target  \
0    cat_dog       0_2  0.879071           0.209024
1    cat_dog  300_2...  0.806782           0.221374
2    cat_dog  300_2...  0.823231           0.217342
3    cat_dog  300_2...  0.819235           0.220152
4    cat_dog  1000_...  0.786160           0.222134
5    cat_dog  1000_...  0.785064           0.220754
6    cat_dog  1000_...  0.771336           0.218937
7   apple...       0_2  0.948937           0.183520
8   apple...  300_2...  0.895386           0.203302
9   apple...  300_2...  0.913538           0.189907
10  apple...  300_2...  0.905061           0.193388
11  apple...  1000_...  0.872271           0.212927
12  apple...  1000_...  0.902965           0.192798
13  apple...  1000_...  0.884651           0.207117
14  kettl...       0_2  0.866195           0.199478
15  kettl...  300_2...  0.755836           0.215254
16  kettl...  300_2...  0.804157           0.200512
17  kettl...  300_2...  0.828589           0.197542
18  kettl...  1000_...  0.728692           0.203333
19  kettl...  1000_...  0.796037           0.197704
20  kettl...  1000_...  0.766867           0.189560
21       age       0_2  0.744383           0.166524
22       age  300_2...  0.674705           0.182267
23       age  300_2...  0.672559           0.180815
24       age  300_2...  0.667609           0.179802
25       age  1000_...  0.604070           0.176085
26       age  1000_...  0.639878           0.175638
27       age  1000_...  0.644659           0.180961
28    gender       0_2  0.841626           0.144702
29    gender  300_2...  0.735146           0.155278
30    gender  300_2...  0.735146           0.155278
31    gender  300_2...  0.728759           0.155624
32    gender  1000_...  0.692404           0.168773
33    gender  1000_...  0.664411           0.153175
34    gender  1000_...  0.702877           0.154704

    clip_score_concept_origin  clip_score_all_target  clip_score_all_origin  \
0   0.147153                   0.292836               0.220889
1   0.147153                   0.293531               0.220889
2   0.147153                   0.297524               0.220889
3   0.147153                   0.299801               0.220889
4   0.147153                   0.283712               0.220889
5   0.147153                   0.291037               0.220889
6   0.147153                   0.285299               0.220889
7   0.170459                   0.239591               0.224809
8   0.170459                   0.256274               0.224809
9   0.170459                   0.246035               0.224809
10  0.170459                   0.246461               0.224809
11  0.170459                   0.261971               0.224809
12  0.170459                   0.249697               0.224809
13  0.170459                   0.268889               0.224809
14  0.150116                   0.270173               0.228619
15  0.150116                   0.261325               0.228619
16  0.150116                   0.260532               0.228619
17  0.150116                   0.266653               0.228619
18  0.150116                   0.245051               0.228619
19  0.150116                   0.257628               0.228619
20  0.150116                   0.248115               0.228619
21  0.149149                   0.255089               0.212237
22  0.149149                   0.277711               0.212237
23  0.149149                   0.278134               0.212237
24  0.149149                   0.273276               0.212237
25  0.149149                   0.268092               0.212237
26  0.149149                   0.271963               0.212237
27  0.149149                   0.274683               0.212237
28  0.095886                   0.252194               0.196829
29  0.095886                   0.240547               0.196829
30  0.095886                   0.240547               0.196829
31  0.095886                   0.243448               0.196829
32  0.095886                   0.234911               0.196829
33  0.095886                   0.223065               0.196829
34  0.095886                   0.229457               0.196829

    clip_score_prompt_target  clip_score_prompt_origin
0   0.242040                  0.289638
1   0.208838                  0.289638
2   0.217856                  0.289638
3   0.220091                  0.289638
4   0.199803                  0.289638
5   0.210823                  0.289638
6   0.207665                  0.289638
7   0.287806                  0.295799
8   0.262634                  0.295799
9   0.261783                  0.295799
10  0.251903                  0.295799
11  0.249979                  0.295799
12  0.249166                  0.295799
13  0.227665                  0.295799
14  0.250206                  0.281521
15  0.186037                  0.281521
16  0.212922                  0.281521
17  0.225166                  0.281521
18  0.175813                  0.281521
19  0.215568                  0.281521
20  0.217752                  0.281521
21  0.238499                  0.266645
22  0.237280                  0.266645
23  0.239538                  0.266645
24  0.234842                  0.266645
25  0.230586                  0.266645
26  0.237260                  0.266645
27  0.235270                  0.266645
28  0.219141                  0.248786
29  0.190244                  0.248786
30  0.190244                  0.248786
31  0.191171                  0.248786
32  0.188837                  0.248786
33  0.167853                  0.248786
34  0.176717                  0.248786

In [12]:
mean_per_fact = df.groupby('blocks', as_index=False).mean(numeric_only=True)

pd.set_option('display.max_colwidth', 15)
#mean_per_fact['blocks'] = ['all', '0', '0-1', '2-3', 'one vec']
mean_per_fact.drop('mean_clip_img_sim', axis=1, inplace=True)
mean_per_fact

,blocks,clip_score_concept_target,clip_score_concept_origin,clip_score_all_target,clip_score_all_origin,clip_score_prompt_target,clip_score_prompt_origin
0,0_2,0.180650,0.142553,0.261976,0.216677,0.247538,0.276478
1,1000_2_diff_m,0.188014,0.142553,0.258678,0.216677,0.216134,0.276478
2,1000_2_diff_s,0.196650,0.142553,0.258747,0.216677,0.209004,0.276478
3,1000_2_norm...,0.190256,0.142553,0.261289,0.216677,0.213014,0.276478
4,300_2_diff_m,0.188771,0.142553,0.264554,0.216677,0.224469,0.276478
5,300_2_diff_s,0.195495,0.142553,0.265878,0.216677,0.217006,0.276478
6,300_2_norma...,0.189301,0.142553,0.265928,0.216677,0.224634,0.276478

## add

### CLIP

In [ ]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/add/generated_images/" # Update to your base path # If your paths start with a shared prefix
concepts = ['hat', 'glasses', 'smile', 'lipstick', "apple"] # Add your actual concepts

facts = ['0_1', 
         '300_1_diff_s',
         '300_1_diff_m',
         '300_1_normals_s',
         '1000_1_diff_s',
         '1000_1_diff_m',
         '1000_1_normals_s',

         ] # Add your fact identifiers

data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Construct the directory name based on your pattern
        # Adjust the underscores "_" below if your naming convention differs
        
        dir_path = os.path.join(root_dir, concept, fact)
        file_path = os.path.join(dir_path, "summary_metrics_part.json")
        
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r') as f:
                    metrics = json.load(f)
                
                # Add concept and fact info to the metric dict for tracking
                metrics['concept'] = concept
                metrics['blocks'] = fact
                
                data_list.append(metrics)
                print(f"✅ Loaded: {concept}, {fact}")
            except Exception as e:
                print(f"❌ Error reading {file_path}: {e}")
        else:
            print(f"⚠️ Missing: {dir_path}")

# --- Create Table ---
df = pd.DataFrame(data_list)

# Reorder columns to put Concept and Fact at the front
cols = ['concept', 'blocks'] + [c for c in df.columns if c not in ['concept', 'blocks']]
df = df[cols]

# Save for plotting
df.to_csv("all_metrics_combined.csv", index=False)
print("\n--- Final Data Table ---")
print(df)

⚠️ Missing: experiments/flux_schnell/add/generated_images/hat/0_2
⚠️ Missing: experiments/flux_schnell/add/generated_images/hat/300_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/hat/300_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/hat/300_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/hat/1000_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/hat/1000_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/hat/1000_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/glasses/0_2
⚠️ Missing: experiments/flux_schnell/add/generated_images/glasses/300_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/glasses/300_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/glasses/300_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/glasses/1000_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/glasses/1000_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/glasses/1000_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/smile/0_2
⚠️ Missing: experiments/flux_schnell/add/generated_images/smile/300_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/smile/300_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/smile/300_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/smile/1000_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/smile/1000_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/smile/1000_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/lipstick/0_2
⚠️ Missing: experiments/flux_schnell/add/generated_images/lipstick/300_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/lipstick/300_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/lipstick/300_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/lipstick/1000_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/lipstick/1000_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/lipstick/1000_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/apple/0_2
⚠️ Missing: experiments/flux_schnell/add/generated_images/apple/300_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/apple/300_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/apple/300_2_normals_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/apple/1000_2_diff_s
⚠️ Missing: experiments/flux_schnell/add/generated_images/apple/1000_2_diff_m
⚠️ Missing: experiments/flux_schnell/add/generated_images/apple/1000_2_normals_s

KeyError: "None of [Index(['concept', 'blocks'], dtype='object')] are in the [columns]"

In [58]:
mean_per_fact = df.groupby('blocks', as_index=False).mean(numeric_only=True)

pd.set_option('display.max_colwidth', 15)
#mean_per_fact['blocks'] = ['all', '0', '0-1', '2-3', 'one vec']
mean_per_fact.drop('mean_clip_img_sim', axis=1, inplace=True)
mean_per_fact

,blocks,clip_score_concept_target,clip_score_concept_origin,clip_score_all_target,clip_score_all_origin,clip_score_prompt_target,clip_score_prompt_origin
0,0_1,0.140180,0.122663,0.262544,0.250715,0.266453,0.268448
1,1000_1_diff_m,0.162568,0.122663,0.258413,0.250715,0.246633,0.268448
2,1000_1_diff_s,0.167514,0.122663,0.261296,0.250715,0.243072,0.268448
3,1000_1_norm...,0.160053,0.122663,0.259345,0.250715,0.246922,0.268448
4,300_1_diff_m,0.158350,0.122663,0.264834,0.250715,0.255043,0.268448
5,300_1_diff_s,0.162344,0.122663,0.268251,0.250715,0.252990,0.268448
6,300_1_norma...,0.159506,0.122663,0.266594,0.250715,0.255558,0.268448

In [59]:
import pandas as pd

# --- Split and Print by Concept ---
print("="*30)
print("DETAILED METRICS BY CONCEPT")
print("="*30)


# Iterate through each unique concept
for concept_name, group in df.groupby('concept'):
    print(f"\n📈 Results for Concept: {concept_name}")
    
    # Select only the relevant columns to keep the printout clean
    # We sort by 'fact' so the comparison is easy to read
    display_cols = ['blocks', 'clip_score_concept_target', 'clip_score_all_target', 'clip_score_prompt_target']
    concept_table = group[display_cols].sort_values(by='blocks')
    
    print(concept_table.to_string(index=False))
    
    # Optional: Save each concept to its own individual CSV
    # concept_table.to_csv(f"metrics_{concept_name.replace(' ', '_')}.csv", index=False)

print("\n" + "="*30)

==============================
DETAILED METRICS BY CONCEPT
==============================

📈 Results for Concept: apple
          blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
             0_1                   0.126921               0.248249                  0.265773
   1000_1_diff_m                   0.129751               0.235997                  0.255668
   1000_1_diff_s                   0.131122               0.243549                  0.257134
1000_1_normals_s                   0.130747               0.238780                  0.254929
    300_1_diff_m                   0.129914               0.249537                  0.269120
    300_1_diff_s                   0.130749               0.252522                  0.267238
 300_1_normals_s                   0.130406               0.251228                  0.269314

📈 Results for Concept: glasses
          blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
             0_1                   0.134375               0.275097                  0.267876
   1000_1_diff_m                   0.172937               0.278679                  0.242744
   1000_1_diff_s                   0.163806               0.268798                  0.236826
1000_1_normals_s                   0.168700               0.277258                  0.241841
    300_1_diff_m                   0.164289               0.278279                  0.245361
    300_1_diff_s                   0.166998               0.279863                  0.244006
 300_1_normals_s                   0.163251               0.278330                  0.247135

📈 Results for Concept: hat
          blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
             0_1                   0.144747               0.256894                  0.260959
   1000_1_diff_m                   0.170211               0.261158                  0.248615
   1000_1_diff_s                   0.186045               0.271247                  0.243068
1000_1_normals_s                   0.164597               0.262563                  0.251316
    300_1_diff_m                   0.167907               0.264732                  0.254040
    300_1_diff_s                   0.173665               0.275259                  0.254751
 300_1_normals_s                   0.170096               0.268627                  0.254110

📈 Results for Concept: lipstick
          blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
             0_1                   0.129901               0.257125                  0.272839
   1000_1_diff_m                   0.165198               0.256302                  0.243552
   1000_1_diff_s                   0.183151               0.258977                  0.231668
1000_1_normals_s                   0.165013               0.258395                  0.242549
    300_1_diff_m                   0.159641               0.266217                  0.258343
    300_1_diff_s                   0.171309               0.265759                  0.249026
 300_1_normals_s                   0.165599               0.271859                  0.260523

📈 Results for Concept: smile
          blocks  clip_score_concept_target  clip_score_all_target  clip_score_prompt_target
             0_1                   0.164957               0.275355                  0.264821
   1000_1_diff_m                   0.174745               0.259928                  0.242587
   1000_1_diff_s                   0.173446               0.263910                  0.246664
1000_1_normals_s                   0.171206               0.259727                  0.243974
    300_1_diff_m                   0.169998               0.265403                  0.248349
    300_1_diff_s                   0.169000               0.267854                  0.249927
 300_1_normals_s                   0.168179               0.262925                  0.246709

==============================

### grounding dino

In [65]:
import os
import json
import pandas as pd

# --- Configuration ---
root_dir = "experiments/flux_schnell/add/generated_images/"
concepts = ['hat', 'glasses', 'smile', 'lipstick', "apple"]
facts = [
    '1000_15_mean_diff_s_only_pooled_0_7', 
    # '300_1_diff_s', '300_1_diff_m', '300_1_normals_s',
    # '1000_1_diff_s', '1000_1_diff_m', '1000_1_normals_s'
]

# The different threshold files you want to track
thresholds = ['0.25', '0.5', '0.6']
data_list = []

# --- Main Logic ---
for concept in concepts:
    for fact in facts:
        # Initialize a row with identifier info
        row = {'concept': concept, 'blocks': fact}
        found_any = False
        
        for t in thresholds:
            file_path = os.path.join(root_dir, concept, fact, 'dino', f"metrics_{t}.json")
            print(file_path)
            if os.path.exists(file_path):
                try:
                    with open(file_path, 'r') as f:
                        metrics = json.load(f)
                        # Use the threshold in the key name for clarity
                        row[f'det_rate_{t}'] = metrics.get('detection_rate')
                        found_any = True
                except Exception as e:
                    print(f"❌ Error reading {file_path}: {e}")
        
        if found_any:
            data_list.append(row)
            print(f"✅ Loaded detection metrics for: {concept}, {fact}")
        else:
            print(f"⚠️ Missing all detection files for: {concept}/{fact}")

# --- Create Table ---
df_det = pd.DataFrame(data_list)

# --- Analysis / Grouping ---

# 1. Mean performance per "Block" across all concepts
mean_per_fact = df_det.groupby('blocks').mean(numeric_only=True)

# 2. Mean performance per "Concept" across all blocks
mean_per_concept = df_det.groupby('concept').mean(numeric_only=True)

print("\n--- Detection Rates by Block ---")
print(mean_per_fact)

print("\n--- Detection Rates by Concept ---")
print(mean_per_concept)

experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/hat/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: hat, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/glasses/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: glasses, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/smile/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: smile, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/lipstick/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: lipstick, 1000_15_mean_diff_s_only_pooled_0_7
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.25.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.5.json
experiments/flux_schnell/add/generated_images/apple/1000_15_mean_diff_s_only_pooled_0_7/dino/metrics_0.6.json
✅ Loaded detection metrics for: apple, 1000_15_mean_diff_s_only_pooled_0_7

--- Detection Rates by Block ---
                 det_rate_0.25  det_rate_0.5  det_rate_0.6
blocks
1000_15_mean...       0.841379      0.668966      0.689655

--- Detection Rates by Concept ---
          det_rate_0.25  det_rate_0.5  det_rate_0.6
concept
apple          0.620690      0.517241           NaN
glasses        0.862069      0.827586      0.827586
hat            0.862069      0.724138      0.724138
lipstick       0.862069      0.620690      0.551724
smile          1.000000      0.655172      0.655172